# Generated by Django 6.0 on 2026-01-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='mood',
            field=models.CharField(blank=True, choices=[('very_happy', '😊 Very Happy'), ('happy', '😀 Happy'), ('neutral', '😐 Neutral'), ('sad', '😞 Sad'), ('very_sad', '😢 Very Sad')], max_length=20, null=True),
        ),
    ]
